<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
</body>
<script type="text/javascript">
  // 1.所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果
  // Promise对象有两个特点：
  // (1).Promise对象的状态不受外界影响。Promise对象存在三种状态：pending（进行中）、fulfilled（已成功）和reject（已失败），只有异步操作的结果，可以决定是哪一种状态，任何其他操作都无法发变这个状态
  // (2).一旦状态改变，就不会再变，任何时候都可以得到这个结果

  // Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

  // 缺点：首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）



  // 2.ES6规定，Promise 对象是一个构造函数，用来生成Promise 实例
  /*

    let promise = new Promise((resolve, reject) => {
      let a = 0;
      if (a) {
        resolve();
      } else {
        reject();
      }
    });

  */
  // Promise构造函数接受一个函数作为参数，该函数有两个参数分别是resolve和reject，它们也是函数
  // (1).resolve函数的作用是，将Promise 对象的状态从“未完成”（pending）==>“成功”（resolved），在异步操作成功时调用，并将异步操作结果，作为参数传递出去。
  // (2).reject函数的作用是，将Promise 对象的状态从“未完成”（pending）==>“失败”（rejected），再异步操作失败时调用，并将操作报错的错误，作为参数传递出去。 

  // Promise实例生成以后，可以用  then  方法分别指定resolved状态和rejected状态的回调函数
  /*

    promise.then(function(value) {
      // success
    },function(error) {
      // failure
    })
    等价于：
    promise.then(
      value => {
        // success
      },
      error => {
        // failure
      }
    )

  */
  // then方法可以接受两个回调函数作为参数
  // 第一个回调函数是Promise对象的状态变为resolved时调用，第二个回调函数是Promise对象的状态变为rejected时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数

  // 一个简单的例子
  function timeOut(ms) {
    return new Promise((resolve, reject) => {
      setTimeout(resolve, ms, 'done')
    })
  }
  timeOut(3000).then((value) => {
    console.log(value)
  })

  // Promise 新建后就会立即执行。

    let promise = new Promise((resolve, reject) => {
      console.log('promise')
      resolve()
    })

    promise.then(() => {
      console.log('resolved')
    })

    console.log('Hi')

    // >>  Promise
    // >>  Hi!
    // >>  resolved

  



  // 3.then用法：可以采用链式写法，即then后在调用另一个then方法，第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数
  /*

    promise()
    .then((res)=>{
        //code
        return res.a;
    })
    .then((res)=>{
        //code
        return res.b;
    })
    .then((res)=>{
        //code
        return res.c;
    })

  */ 



  // 4.catch用法：是用于指定发生错时的回调函数，即为Promise从未完成到失败的回调函数
  /*

  let promise = new Promise(function(resolve, reject) {
    reject();
  });
  promise.catch((error) => {
    console.log(error)
  })

  */
  // (1). 另外，then方法指定的回调函数，在运行中抛出错误时，也会被catch方法捕获
  let promise1 = new Promise((resolve, reject) => {
    throw new Error('testError')
  })

  promise1.catch((error) => {
    console.log(error)
  })

  // (2). 如果 Promise 状态已经变成resolved，再抛出错误是无效的
  let promise2 = new Promise((resolve, reject) => {
    resolve('ok')
    throw new Error('resolveError')
  })

  promise2.then(
    (value) => {
      console.log(value)
    }
  ).catch(
    (error) => {
      // 因为已经resolve了，所以catch不到上面的throw error 因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了
      console.log(error)
    }
  )

  // (3).Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获
  /*
  
    getJSON('/post/1.json').then(function(post) {
      return getJSON(post.commentURL);
    }).then(function(comments) {
      // some code
    }).catch(function(error) {
      // 处理前面三个Promise(一个由getJSON产生，两个由then产生)产生的错误
    });

  */
  
  // (4).一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法
  /*
  
    // bad
    promise.then((data) => {
      // success
    }, (error) => {
      // error
    })

    // good good good
    promise.then(() => {
      // success
    }).catch((error) => {
      // error
    })
  
  */


  // (5).all用法：提供了并行执行异步操作的能力，并且在所有异步操作完成后才执行回调函数 ==> 【谁跑的慢，以谁为准执行回调】
  function runAsync1(){
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            console.log('异步任务1执行完成');
            resolve('随便什么数据1');
        }, 1000);
    });
    return p;            
  }
  function runAsync2(){
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            console.log('异步任务2执行完成');
            resolve('随便什么数据2');
        }, 2000);
    });
    return p;            
  }
  function runAsync3(){
      var p = new Promise(function(resolve, reject){
          //做一些异步操作
          setTimeout(function(){
              console.log('异步任务3执行完成');
              resolve('随便什么数据3');
          }, 5000);
      });
      return p;            
  }

  Promise.all([runAsync1(), runAsync2(), runAsync3()]).then(res => {
    // 等到 runAsync3() 执行完  才会执行此回调
    console.warn('谁跑的慢，以谁为准执行回调！');
    console.log(res)
  })
  // 用Promise.all来执行，all接收一个数组作为参数，里面的值最终会返回Promise对象。这样三个异步操作的并行执行，等到它们都执行完后才会进入then里面。all会把三个异步操作的结果放到一个数组中传给then。也就是说有了all，你就可以并行执行多个异步操作，并且在一个回调函数中处理所有异步操作返回的数据
  // 有一个场景很适用这个，在素材比较多的应用，预先加载需要用到的各种资源，所有加载完后，我们在进行页面的初始化



  // (6).race用法：同样是并行异步操作，与all方法不同的是，率先完成异步操作的就立马执行回调函数 ==> 【谁跑的快，以谁为准执行回调】
  Promise.race([runAsync1(), runAsync2(), runAsync3()]).then(res => {
    // runAsync1() 执行完  就会执行此回调
    console.warn('谁跑的快，以谁为准执行回调！');
    console.log(res);
  })
  // 在then里面回调开始执行时，runAsync2()和runAsync3()并未停止，仍旧再执行，于是1秒后，输给了他们的结束标志
</script>
</html>